### ISSUE TITLE
Tinkers MechWorks and QuantumFlux

### ISSUE THREAD

**Issue by fistidgious** [AlmuraDev/Almura#128]
tinkers mechworks:- adds some cool blocks to tinkers mod include a drawbridge use dispensers

http://www.curse.com/mc-mods/minecraft/tinkers-mechworks/2229984

quantumflux:- a realy awsome power mod that has been developed to ease on power creation the the recipies in it can be exspensive to get to high end the use`s r awsome works with all machines i have tested in s/p

http://www.curse.com/mc-mods/minecraft/228609-quantumflux/2255627

**Comment by mcsnetworks** [comment]
Both of these scream lag because they introduce "wireless" abilities.  Wireless only works if the chunks on both sides of the bridge are active (usually).

These are gonna need to be tested heavily and both introduce new issues where Residence is concerned.

The new draw-bridge doors I'm sure don't act as normal doors.  The new armor and items that Flux adds would all have to be added to existing protections.

Also:  Have either of these mod makers said they are going to support 1.9 or above?  I'm putting a full stop on new mods on the server unless their developers are committed to moving past 1.7.10.

**Comment by fistidgious** [comment]
got this from glassmaker auther of mechworks

Yes, You can use Tinkers' Mechwork in your pack. :)

I'm planning on keeping the mod and updating it to 1.9 :)

Jotato quantum flux mod auther mailed me this

No permissions are needed to use it.

As far as updates, the mod has a dependency on CofhLib. I can't update any faster then CoFH updates that dependency. If/when they update to 1.9 I will do it as well.

anything else i need to find out ???

**Comment by mcsnetworks** [comment]
Will discuss this again once Almura 3.0 is finished.
