### ISSUE TITLE
Sign Shop malfunction with thaumcraft items after server restart

### ISSUE THREAD

**Issue by rcnsol** [AlmuraDev/Almura#200]
I noticed this a few days ago and have been closely watching this since then to give more specifics.

Problem: Every time the server does its daily restart, afterwards the linked [Buy] signs give the message "Shop is out of stock" on right-click and switches from blue to red (noted the chests are still full). Prior to the restart it works fine. After destroying the chest containing the item and re-doing the link process the functionality is restored (until the next restart)
This occurs only (in my case, not sure if other items are affected to) with Thaumcrafts Crystallized Essence of any type. I assume it has to do with the way Thaumcraft saves the information what type it is.

Item: THAUMCRAFT_ITEMCRYSTALESSENCE  - 5038:0 

(robitect)

**Comment by Dieheart3** [comment]
It also is what breaks my map shops... I could sell atlaes/maps fine to start I even tested it. Something kept breaking the shops later. Maps would be like your shop ^ and atlases would be blank with no maps inside... Now I know what did that, maybe there is hope for my shop after all.

**Comment by mcsnetworks** [comment]
Question:  The only thing I can think of that is causing this issue is the fact the item stack contains a large array of NBT data or something like it.  Regardless it appears that SignShop isn't respecting the values and therefore it dumps it.  If you are willing you can work with me to try and solve the issue with a change to the signshop code.  

PM me in game and we'll try if you have time.  Closing ticket for now.
