### ISSUE TITLE
TConstruct bug

### ISSUE THREAD

**Issue by infiswifr** [AlmuraDev/Almura#233]
The recipe for the TConstruct belt and knapsack is mixed up. The recipe for the belt and knapsack seem a bit illogical.

Sorry for the poor explaination,

infiswift

**Comment by Wolfeyeamd0** [comment]
They are not mixed up - it's just the recipes seem weird to some people.

**Comment by mcsnetworks** [comment]
We are already on the last build for 1.7.10 and I don't think I can fix this as it seems to be a recipe issue with their mod.  We can only hope its fixed in newer version once we move off of 1.7.10.

**Comment by Wolfeyeamd0** [comment]
This wasn't an actal bug- it was more an opion on how the recipe should be.

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Mon, Jan 11, 2016 at 5:06 PM -0800, "Dockter" <notifications@github.com<mailto:notifications@github.com>> wrote:


We are already on the last build for 1.7.10 and I don't think I can fix this as it seems to be a recipe issue with their mod. We can only hope its fixed in newer version once we move off of 1.7.10.

-
