### ISSUE TITLE
A Shop sign error, not really a bug...

### ISSUE THREAD

**Issue by Endante** [AlmuraDev/Almura#234]
The Blacksmith shop in the Asgard castle at x:-1304 z:-1078 has, what I believe to be, a typo error in the least expensive repair sign.  I believe you intended Wood_Weapon, instead it says Diamond_Weapon.

If I am correct that will allow someone to repair their Diamond weapon for the $4500, instead of the $12500 that is listed in the sign right below it, that also is designated Diamond_Weapon.

**Comment by Endante** [comment]
I tried to PM ~Dockter in game, but it kept telling me I was talking to myself.  :)

**Comment by Wolfeyeamd0** [comment]
I broke the sign sign since it was linked to Diamond Weapons.  It doesn't really make sense to have one for wood or stone weapons, so I just removed the sign instead.


Dockter's ingame name is mcsnetworks  - so if you are trying to PM him that is the name you should use.  You can see everyone who is online's ingame names if you hit the 'Tab' button.

Thank you!
