### ISSUE TITLE
Need assistance re-implementing "Animal-Heat" configuration and Mixin

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/Almura#388]
In 1.7.10 we had this:

https://github.com/AlmuraDev/Almura/blob/master/src/main/java/com/almuradev/almura/mixin/client/renderer/entity/MixinRendererLivingEntity.java

We would render the name above an animals head and change its color based on animal.isInLove()

In 1.12.2, the implementation has to be a little different.

Within client.renderer.entity there is a Render class, this is an abstract class so I couldn't figure out how to make a mixin to handle this.  

First off I believe that we need to inject at the start of the "canRenderName" method and return true if a configuration value is turned on to display animal names or something like it.

Secondly I believe to need to then frankly overwrite the renderLivingLabel method (or add to what title branch has) to implement what we had for changing the color of the name.  Some additional farming related values would be helpful here, age of animals etc.

**Comment by Zidane** [comment]
Much like Titles, this cannot return as it was. The Mixin needs to target the specific Render classes the farm animals are using (RenderChicken). Reasoning here is this is extremely hot code and we should only touch the specific farm animals (mixing into LivingBase hits too many ones we don't care about).

Otherwise, this isn't a hard change. May take a moment or two of thought to do a non-overwrite. I'd like to if at all possible as it gives us some insurance against the inclusion of a future mod that may mess with these render classes (or if Optifine ever decides to do so).

**Comment by Zidane** [comment]
So I've put together some initial code for doing this. I can finish it up (sans configuration stuff, you can do that) but it won't be pretty as the client is no longer told the actual inLove value in 1.12.2 (it is now always 0). This can be done completely with Sponge but that is pending the ChangeDataHolderEvent.ValueChange implementation which is a whole another massive affair and subject in and of itself.

https://github.com/AlmuraDev/Almura/tree/feature/sexy-time

**Comment by Dockter** [comment]
Added to Almura 3.0 - 1.5 Ticket.
